import type { Metadata } from "next";
import { Geist, Geist_Mono, Philosopher } from "next/font/google";
import "./globals.css";
import "keen-slider/keen-slider.min.css"
import Navbar from "@/components/nav/navbar";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const philosopher = Philosopher(
  {
    variable: '--font-philosopher',
    subsets: ["latin"],
    weight: ['400', '700']
  }
);


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${philosopher.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="pt-28 md:pt-56">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
